<h2>Prepare</h2>

<?php
/**
 * @file
 * Allow users to convert standard texts to texts with gender placeholders.
 */

use GuzzleHttp\Client;

// Some default text.
$text = 'One midday when, after an absence of two hours, she came into the room, she beheld the chair empty. Down she flopped on the bed, and sitting, meditated. "Now where the devil is my man gone to!" she said.';
if (isset($_POST['text'])) {
  $text = $_POST['text'];
}
echo '
<div class="container prepare">
  <form action="' . $base_url . 'prepare" method="POST">
    <div class="row">
      <div class="six columns">
        <label for="text">Paste original text with no placeholders.</label>
        <textarea class="u-full-width textbox" placeholder="Place words here..." name="text">' . $text . '</textarea>
      </div>
      <div class="six columns">
        <input class="button-primary" type="submit" name="json" value="Replace with placeholders" />';
          if (isset($_POST['text'])) {
            $client = new Client();
            $res = $client->request('POST', $api, [
              'form_params' => [
                'placeholders' => $_POST['text'],
              ],
            ]);
            if ($res->getStatusCode() == '200') {
              $with_placeholders = ($res->getBody());
            }
            echo '<p>' . $with_placeholders . '</p>';
            echo '<div class="panel"><p>Placeholders have been autogenerated. You will now need to replace each "person" instance with the correct character and add a legend. The following page will allow you to paste in your completed text and test the interaction of that text with the legend.</p><a href="' . $base_url . 'test" class="button button-primary">Test ></a>';
          }
      echo '
      </div>
    </div>
  </form>';
